development:
  clients:
    default:
      database: urlminder_development
      hosts:
        - localhost:27017
  # Configure available database sessions. (required)
  options:
test:
  sessions:
    default:
      database: urlminder_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

production:
  clients:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
  options:
